// <auto-generated />
namespace ITRACK.models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Colors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Colors));
        
        string IMigrationMetadata.Id
        {
            get { return "201510161010136_Colors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
